### ISSUE TITLE
Creating the Thai version in the same concept of Missing Semester

### ISSUE THREAD

**Issue by heyfirst** [missing-semester/missing-semester#133]
Hi there,

I am Kanisorn from Thailand. I learned this course and I think this is really good content here. I would like to ask that I will create the Thailand CS Missing Semester and re-create contents to Thai.

I plan to use re-create content because I love the concept of Missing Semester but we might modify or create by our own style. All is free, serve on GitHub Pages via http://docusaurus.io/. And here we have fews Thai contributers to help to create/validate Thai contents. We will have more or less lesson from your current course. 

I am here because I concern about the license. Would I need to strict on the same license here.

Thanks.

**Comment by lifez** [comment]
@heyfirst I'm in!

**Comment by bazsup** [comment]
@heyfirst I'm in!

**Comment by anishathalye** [comment]
Yes, you can read more about our content license here: https://missing.csail.mit.edu/license/

The relevant clause here is the "ShareAlike":

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by heyfirst** [comment]
So I think I can do with mention this 🙂 In Thailand, many tech people are not good in English. Would be nice if you have some resource for them. Hope I can share you back the result some days soon.

Thank you very much.

**Comment by anishathalye** [comment]
Yes, please let us know when you have something up, and we can link to it in our list of [translations](https://missing.csail.mit.edu/#translations).

**Comment by heyfirst** [comment]
@anishathalye Sure, I will let you know soon. Let's me kick-off it next week. (Thailand have an holiday from 13-15 April)

By the way, I see our Serbian folks customized their styling. That's awesome! 👍🏻 I have some idea for Thailand site though 🙂

**Comment by anishathalye** [comment]
Going to close this issue now. Please send a new PR or open an issue when you want to add a link to the translated version.
