### ISSUE TITLE
The path of Vim's plugin

### ISSUE THREAD

**Issue by waynezhangw** [missing-semester/missing-semester#137]
In Editors (Vim) course, 

why suggest to put plugins in ~/.vim/pack/vendor/start instead of ~/.vim/pack/git-plugins/start(from vimawesome.com) or ~/.vim/bundle? What is the difference between these paths?

And how the vim notice these plugins? Or how does the vim know where to find these plugins?

**Comment by anishathalye** [comment]
You can look at `:help packages` to get more info on Vim 8.0 native package loading. The name "vendor" is arbitrary. It seems that vimawesome.com has chosen "git-plugins".

From the vim help pages:

```
Let's assume your Vim files are in the "~/.vim" directory and you want to add a
package from a zip archive "/tmp/foopack.zip":
        % mkdir -p ~/.vim/pack/foo
        % cd ~/.vim/pack/foo
        % unzip /tmp/foopack.zip

The directory name "foo" is arbitrary, you can pick anything you like.
```

`~/.vim/bundle`, on the other hand, is a [Pathogen](https://github.com/tpope/vim-pathogen)-ism.

**Comment by waynezhangw** [comment]
Thanks for the explanation.
