### ISSUE TITLE
Alternative word for metaprogramming

### ISSUE THREAD

**Issue by Elaro** [missing-semester/missing-semester#160]
Metaprogramming, as the lecture correctly points out, is generally understood to mean "programming programs that write programs", and is (or should be) considered a field of AI. I'm currently exploring that specific topic, so using it for other things will lead to confusion.

For the Build Systems/Continuous Integration lecture, why not call it **Periprogramming**, from the ancient Greek for "around", ie the things we do around programming, instead?

**Comment by jonhoo** [comment]
We're not going to change content from the 2020 course, but it's good to have recommendations for a potential future iteration of the course, thanks!

**Comment by chapmanjacobd** [comment]
yeah when I clicked on metaprogramming I thought it would be about dynamic programming

rather than creating a new word, I think it should be titled "Build Systems/Continuous Integration"
