### ISSUE TITLE
Data Wrangling | journalctl doesn't work on WSL without configuration

### ISSUE THREAD

**Issue by t-miller** [missing-semester/missing-semester#181]
Questions 4 and 5 in the Data Wrangling lesson with OOTB WSL. I was able to get it up and running using the instructions [here](https://github.com/DamionGans/ubuntu-wsl2-systemd-script). It may be worth noting this for future versions for ease of use,

**Comment by anishathalye** [comment]
I wonder if it's worth telling people how to set up systemd on WSL (does it cause any complications?), or just say that people shouldn't bother / use a real Linux system for this exercise if they want to do it.

**Comment by linhns** [comment]
@anishathalye @t-miller Since Microsoft has rolled out systemd support for WSL, there should be no problem with this exercise anymore.
