### ISSUE TITLE
Security and Cryptography | `sha1sum` doesn't work

### ISSUE THREAD

**Issue by Chuhao95** [missing-semester/missing-semester#221]
Thanks for this great lecture!

In Security and Cryptography lecture, `sha1sum` was used for demonstration. 

But I found `shasum` worked in my zsh shell instead of `sha1sum`.

I tried my bash shell where `sha1sum` also didn't work.

**Comment by JJGO** [comment]
What OS are you using? In macOS, debian and ubuntu, `sha1sum` is available
