### ISSUE TITLE
Debugging and Profiling | Linter

### ISSUE THREAD

**Issue by Chuhao95** [missing-semester/missing-semester#222]
Thanks for this beneficial lecture!

I found it was tough for newbies like me to install the **linter plugin for Vim** which was mentioned in the exercise of *Debugging and Profiling*.

Maybe elaborating on this topic a bit more in future would be helpful, as this feature looks very useful.

**Comment by JJGO** [comment]
Well, part of the exercise is figuring out how to install the linter in your editor of choice. Even when just considering vim, there isn't a single solution as many plugins are available, e.g. ale, coc.nvim, native lsp, &c
