### ISSUE TITLE
Typo on lecture 4 "Data-wrangling" notebook

### ISSUE THREAD

**Issue by NoviceButLove** [missing-semester/missing-semester#233]
This screenshot show the wrong word. 
---

![image](https://github.com/missing-semester/missing-semester/assets/117814812/0215cb01-458b-475c-a7c4-ab6da5bafeeb)

---
I don't find the meaning of this word *trixy*, so I guess maybe it is a typo.
---

![image](https://github.com/missing-semester/missing-semester/assets/117814812/115c014f-a280-4abe-aeb6-4691a2acfc5f)

---

**Comment by macronym** [comment]
This is intentional, according to this conversation: 

https://github.com/missing-semester/missing-semester/pull/84

**Comment by NoviceButLove** [comment]
Thank you. I am going to try to understand its meaning.

**Comment by macronym** [comment]
The word here that would make sense would be 'tricky'. I'm not sure why they used 'trixy' here, but maybe it's some sort of inside joke. I don't think it's a real word.

**Comment by NoviceButLove** [comment]
Great! I agree your advice. 

Should I reopen this issue to consult other's opinions?

**Comment by macronym** [comment]
No don't reopen it because it's intentionally misspelled.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jonhoo** [comment]
"trixy" is mostly a slightly-fun twist on the word "tricky" to inject some humor into the material. If you found it actually confusing, I'm open to changing it, but if it just read a little "weird", then I'm okay with that :)

**Comment by anishathalye** [comment]
We've had several separate PRs where people were confused about this word, so maybe we should change it?

**Comment by jonhoo** [comment]
Fair enough :p

**Comment by anishathalye** [comment]
Updated in ﻿﻿3a5651a42e68e85a7fbdd6b387df47af96146a61. End of an era.

**Comment by NoviceButLove** [comment]
> "trixy" is mostly a slightly-fun twist on the word "tricky" to inject some humor into the material. If you found it actually confusing, I'm open to changing it, but if it just read a little "weird", then I'm okay with that :)

Thanks. I can guess the word "tricky" but may not comprehend the humor in it.
