### ISSUE TITLE
Port Frwd Imgs Not Loading /2020/command-line/

### ISSUE THREAD

**Issue by BakirGracic** [missing-semester/missing-semester#286]
2 images demonstrating local and remote port forwarding are not loading on live website (placeholder image with alt attribute gets rendered) - [see image at the bottom]

inspecting the image and visiting the link in new tab works fine (i can see the image)

please recreate on your devices to remove any doubt if my adblock or other software may be blocking domains that the images are hosted on (probably unlikely since I tested with everything turned off)

notice
this is a small issue, just wanted to point it out to make this amazing lecture even more perfect!

![image](https://github.com/missing-semester/missing-semester/assets/79216774/317380df-8410-4db8-9feb-54d8a3b27484)

**Comment by jonhoo** [comment]
Ah, looks like they've started disallowing hotlinking to images on those domains (browser gives a 403 Forbidden when it tries to load them through `<img>`). The images are originally from [this StackOverflow post](https://superuser.com/questions/677944/how-do-i-ssh-tunnel-port-forward) — we'll have to copy them into our repository to avoid the hotlinking (or generate our own images and do the same thing).

**Comment by BakirGracic** [comment]
I've made a quick fix, you can check pull requests

**Comment by jonhoo** [comment]
Fixed in #289
