### ISSUE TITLE
zsh history substring search vs. autosuggestions

### ISSUE THREAD

**Issue by cmnord** [missing-semester/missing-semester#4]
The [shell tools lecture](https://missing.csail.mit.edu/2020/shell-tools/) references [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search), but I believe it's referring to [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions). zsh-history-substring-search enables UP/DOWN to page through command history, but zsh-autosuggestions enables the dynamic autocomplete.

It might be helpful to link to both plugins!

**Comment by anishathalye** [comment]
Yeah, I think you're right. I agree that it would be helpful to link to both. Want to send us a pull request?

**Comment by cmnord** [comment]
Created #5!
