### ISSUE TITLE
A mirror site for Chinese translation 

### ISSUE THREAD

**Issue by hanxiaomax** [missing-semester/missing-semester#46]
Thank you guys, this is such a great course!  It is even more helpful to  self-taught engineers like me. so I really want to contribute and what I can do is to translate this into Chinese to make it easier for Chinese developers to learn. 
so I create a mirror site of your project here : https://missing-semester-cn.github.io/ as the Chinese version and if it looks good to you, please can you consider to link it from yours? 

Though the site is not finished yet, I will translate one or two lecture notes per week, so I think it will be finished very soon. 

BTW, you can check the source code here: https://github.com/missing-semester-cn/missing-semester-cn.github.io

**Comment by anishathalye** [comment]
Thank you! I opened #47, will merge soon after talking with Jon and Jose.

**Comment by anishathalye** [comment]
Merged, thanks again!

**Comment by hanxiaomax** [comment]
cool! Thank you!
