### ISSUE TITLE
`git commit -C` for the last exercise in Security

### ISSUE THREAD

**Issue by Ivan-Kim** [missing-semester/missing-semester#56]
I have been struggling with this exercise for a while to see how `git commit -C` could be used to sign a git commit since according to its man page, it takes an existing commit object, and reuse the log message and the authorship information (including the timestamp) when creating the commit.

Isn't `git commit -S` the command used to sign a git commit? Worked that way when I tried at least. Not sure if I overlooked something or is it a typo maybe?

**Comment by anishathalye** [comment]
Yes, that is a typo. Thank you for pointing it out. Fixed in 923ff93dab5b7235920379e058a54a74ef452ce1.
