### ISSUE TITLE
Desired size of PRs

### ISSUE THREAD

**Issue by bewuethr** [missing-semester/missing-semester#63]
As I'm reading through the lectures and find typos or mistakes, I'd like to help improve the Missing Semester and let you know about them. How do you prefer contributions?

- Issues
- Large-ish PRs (one per lecture)
- Small PRs (one per mistake)
- Some other way?

**Comment by anishathalye** [comment]
Large-ish PRs (one per lecture) are preferred (but any form is accepted).
