### ISSUE TITLE
Build fail issue

### ISSUE THREAD

**Issue by hasantezcan** [missing-semester/missing-semester#74]
![image](https://user-images.githubusercontent.com/32804505/86512328-da058780-be09-11ea-80a4-b542fc299573.png)

**Comment by anishathalye** [comment]
Thanks, fixed.

**Comment by sadikkuzu** [comment]
Solved by https://github.com/missing-semester/missing-semester/commit/0c5de338573ff88c44ec492e2925cc284a2c2365 and https://github.com/missing-semester/missing-semester/commit/8ab8905944349ad39b66e789122ba911d25ab441.

Here are the corresponding build reports: [#87](https://travis-ci.com/github/missing-semester/missing-semester/builds/174286986), [#88](https://travis-ci.com/github/missing-semester/missing-semester/builds/174287105).
