### ISSUE TITLE
Misuse of the term "metaprogramming"

### ISSUE THREAD

**Issue by remysucre** [missing-semester/missing-semester#9]
Lecture 8 should not be called "metaprogramming" which is a [well-established term](https://en.wikipedia.org/wiki/Metaprogramming) that refers to a technique that treats programs as data. It seems that lecture is mostly about building software, so why not call it that?

**Comment by jonhoo** [comment]
The lecture covers build systems, testing, continuous integration, version numbering, dependency management, and a bunch of other bits and pieces, so it is not exclusively about building software. Rather, it is about the processes surrounding programming, which metaprogramming aptly describes. Sure, the term has another meaning, but that does not make it inappropriate for use here, especially given that the very first thing the lecture does is explain why we called it that :)

**Comment by remysucre** [comment]
I agree building doesn't encompass all of that, but I challenge you to find a better term, perhaps "integrating software"? At least, I think it's important to point out how the term "metaprogramming" is usually used.
