### ISSUE TITLE
Tool and resource suggestions

### ISSUE THREAD

**Issue by koernepr** [missing-semester/missing-semester#91]
Some tool and resource suggestions:

**Git:**
- [tig](https://github.com/jonas/tig) is really nice as a tool between using `git` on the command-line and using a GUI. It's especially helpful for visualizing the commit graph of smaller repositories (`tig --all`) and even has a periodic-refresh feature (`refresh-mode=periodic` combined with `refresh-interval`). The latter could be used to show the current commit history, e.g. in a `tmux` split, while working with the repository. I only recently discovered the auto-refresh feature and thus didn't really use it so far, but the alternative variant having `watch git log --graph ...` in a `tmux` split, alongside `watch tree .git`, was quite nice when explaining Git.
Caveat: relatively dense keyboard mapping, i.e. simply pressing random keys might not be the best idea ...
- [The Git Parable](https://tom.preston-werner.com/2009/05/19/the-git-parable.html) as background reading
- [Think like (a) Git](http://think-like-a-git.net/) for a relatively short overview of various topics, including branching and merging

**Data wrangling:**
- [visidata](https://github.com/saulpw/visidata) also is a TUI tool, but looks *very* helpful for working with tabular data in a terminal and seems to be a tool which is worth having heard of. Unfortunately I cannot say much about its reliability so far since I also discovered it quite recently.
[Lightning talk](https://www.youtube.com/watch?v=N1CBDTgGtOU), [website](https://www.visidata.org/), [tutorial](https://jsvine.github.io/intro-to-visidata/)
Caveat: the use of `yaml.load()` in the stable version may lead to code execution when a malicious YAML file is loaded ([issue](https://github.com/saulpw/visidata/issues/326); also depends on the pyyaml version in use)

**Comment by anishathalye** [comment]
Thank you for the suggestions. We're going to avoid adding these to the 2020 version of the notes, because the lists of resources are already pretty long, and we don't want to overwhelm beginners. We'll keep these suggestions in mind for the next iteration of the course.
