### ISSUE TITLE
solution for excercises

### ISSUE THREAD

**Issue by phucnsp** [missing-semester/missing-semester#92]
Hello,

I am following your course and I am stuck at some points. I would like to ask whether the solutions in each chapter exist somewhere?

**Comment by anishathalye** [comment]
We haven't written solutions, and we don't plan to. If you are stuck on something in particular, you can send us an email describing what you've tried so far, and we can try to help you out.

**Comment by jonhoo** [comment]
@anishathalye I wonder if we should document this somewhere that's easy to find given the number of questions we get about it?

**Comment by anishathalye** [comment]
Sure, that sounds good. What is a good place for it?

**Comment by jonhoo** [comment]
Maybe it should go on the front page?

**Comment by payangf** [comment]
> Hello,
> 
> I am following your course and I am stuck at some points. I would like to ask whether the solutions in each chapter exist somewhere?

# GitHub
> Hello,
>
> Am I following this course and I am stuck with this point of views. I would like to solve this by github itself?

**Comment by anishathalye** [comment]
Hi, we don't release official solutions, but I think some people have written solutions and posted them on the internet, so you can try finding them using a search engine.

**Comment by anishathalye** [comment]
> I would like to solve this by github itself?

Let's try using https://github.com/missing-semester/missing-semester/discussions as a Q&A forum for this purpose.
