### ISSUE TITLE
-d option doesn't exist on macOS for xargs [Lecture 2] 

### ISSUE THREAD

**Issue by ashutoshpathak200** [missing-semester/missing-semester#93]
In Shell Tools and Scripting lecture, Q4 of exercises states in hint 

> check `-d` flag for `xargs`

This doesn't work on macOS as it is a GNU extension. Had to figure this out. The alternative is using `-print0` option on `find` and `-0` option on `xargs`.

**Comment by anishathalye** [comment]
Thank you for pointing this out. We've tried to clarify BSD vs GNU coreutils in 90dfe097098886a7737749734341a45283798a5c
.
